server:
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    hikari:
      pool-name: HikariCp
      maximum-pool-size: 2
      minimum-idle: 2
    username: sh
    password: 1234
    url: jdbc:mysql://127.0.0.1:4004/sh?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.dialect.storage_engine: innodb
    open-in-view: false
  properties:
    hibernate:
      format_sql: true
app:
  access-token:
    secret: scYkHdNTawutmI1SmLO5l186hFmohGIWB4ECIWrjd453eWWW2a6HezjqPIfpuuD5
    expiration-msec: 600000 #10분
    refresh-expiration-msec: 1728000000 #14일
logging.level:
  org.hibernate.SQL: debug